export const SET_YOUTUBE_LOADER = "SET_YOUTUBE_LOADER";
export const REMOVE_YOUTUBE_LOADER = "REMOVE_YOUTUBE_LOADER";
export const SET_YOUTUBE_MESSAGE = "SET_YOUTUBE_MESSAGE";
export const REMOVE_YOUTUBE_MESSAGE = "REMOVE_YOUTUBE_MESSAGE";
export const SET_YOUTUBE_ERRORS = "SET_YOUTUBE_ERRORS";
export const REMOVE_YOUTUBE_ERRORS = "REMOVE_YOUTUBE_ERRORS";
export const SET_YOUTUBE_CONTENT = "SET_YOUTUBE_CONTENT";
